services:
  - type: web
    name: apple-pay-workshop
    env: node
    buildCommand: yarn install
    startCommand: yarn start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 